### PR TITLE
include offline capability

### PR DESCRIPTION
**Pull request by matthiaszimmermann**
this pull requests makes the repo capable to be run in offline model. the only thing that is missing are the model weights which need to be downloaded externally.

the changes to the original repository are summarized at the end of the updated README file.

### CODE REVIEW

**Comment by sharonzhou** [comment]
Do you want to link the model weights — they're from this repo? https://github.com/val-iisc/lsc-cnn

From their README: https://drive.google.com/drive/folders/1hlJg4ux_BI3z_8zRdwwE7oQoumzSYIEg

**Comment by matthiaszimmermann** [comment]
might not fully understand your comment. yes, i took the model weights from the links provided in your comments and documented that in the readme file [1] for the model directory. what is your suggestion? to more explicitly mention this in the README.md file of the blm repository?

[1] https://github.com/matthiaszimmermann/blm/blob/master/app/model/readme.txt

**Comment by sharonzhou** [comment]
I meant if you wanted to push the model weights directly. This looks great! Because we want this open source repo to show what's powering our website (so people can see we're not saving anything, for example), I'd suggest requesting a merge in this PR into a separate branch, e.g. `offline` on stanfordmlgroup and I can add something to the master README to check it out for the offline version, with attribution of course to you. Thanks :)

**Comment by matthiaszimmermann** [comment]
pushing the pretrained model weights file to github doesn't work (file too large). we could try git large file storage [1] or pytorch hub [2]. git lfs seems a bit more straight forward. however, both options add complexity for the end user. do you see any other options?

pushing to an `offline` branch is of course possible once your repo does have such a branch.

please let me know what works best for your side.

[1] https://git-lfs.github.com/
[2] https://pytorch.org/hub/

**Comment by sharonzhou** [comment]
Looks 💯  Merging this now

**Pull request merged**
